In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.metrics import mean_squared_error
from sklearn.feature_selection import SelectKBest, f_regression, RFE
import statsmodels.api as sm

In [5]:

df = pd.read_csv('Data_Marketing_Customer_Analysis_Round3 (1).csv')

In [6]:
df

,region,customer_lifetime_value,response,coverage,education,effective_to_date,month,employment_status,gender,income,...,months_since_policy_inception,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size
0,central,4809,no,basic,college,2/18/11,feb,employed,m,48029,...,52,0,9,corporate auto,corporate l3,offer3,agent,292,four-door car,medsize
1,west region,2228,no,basic,college,1/18/11,jan,unemployed,f,92260,...,26,0,1,personal auto,personal l3,offer4,call center,744,four-door car,medsize
2,east,14947,no,basic,bachelor,2/10/11,feb,employed,m,22139,...,31,0,2,personal auto,personal l3,offer3,call center,480,suv,medsize
3,north west,22332,yes,extended,college,1/11/11,jan,employed,m,49078,...,3,0,2,corporate auto,corporate l3,offer2,branch,484,four-door car,medsize
4,north west,9025,no,premium,bachelor,1/17/11,jan,medical leave,f,23675,...,31,0,7,personal auto,personal l2,offer1,branch,707,four-door car,medsize
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10684,central,15563,no,premium,bachelor,1/19/11,jan,unemployed,f,61541,...,40,0,7,personal auto,personal l1,offer3,web,1214,luxury car,medsize
10685,north west,5259,no,basic,college,1/6/11,jan,employed,f,61146,...,68,0,6,personal auto,personal l3,offer2,branch,273,four-door car,medsize
10686,central,23893,no,extended,bachelor,2/6/11,feb,employed,f,39837,...,63,0,2,corporate auto,corporate l3,offer1,web,381,luxury suv,medsize
10687,west region,11971,no,premium,college,2/13/11,feb,employed,f,64195,...,27,4,6,personal auto,personal l1,offer1,branch,618,suv,medsize
10688,central,6857,no,basic,bachelor,1/8/11,jan,unemployed,m,68942,...,1,0,3,personal auto,personal l1,offer4,web,1021,suv,medsize

In [12]:
X = data.drop('total_claim_amount', axis=1)
y = data['total_claim_amount']

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train = pd.DataFrame(X_train, columns=X.columns)
X_test  = pd.DataFrame(X_test, columns=X.columns)

X_train = X_train.select_dtypes(include=np.number)
X_test  = X_test.select_dtypes(include=np.number)

In [21]:
def feature_selection_pvalue(X, y, alpha=0.05):
    X_ = sm.add_constant(X)
    model = sm.OLS(y, X_).fit()
    p_values = model.pvalues[1:]
    selected_features = X.columns[p_values < alpha]
    return selected_features

In [23]:
X

,region,customer_lifetime_value,response,coverage,education,effective_to_date,month,employment_status,gender,income,...,months_since_last_claim,months_since_policy_inception,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,vehicle_class,vehicle_size
0,central,4809,no,basic,college,2/18/11,feb,employed,m,48029,...,7,52,0,9,corporate auto,corporate l3,offer3,agent,four-door car,medsize
1,west region,2228,no,basic,college,1/18/11,jan,unemployed,f,92260,...,3,26,0,1,personal auto,personal l3,offer4,call center,four-door car,medsize
2,east,14947,no,basic,bachelor,2/10/11,feb,employed,m,22139,...,34,31,0,2,personal auto,personal l3,offer3,call center,suv,medsize
3,north west,22332,yes,extended,college,1/11/11,jan,employed,m,49078,...,10,3,0,2,corporate auto,corporate l3,offer2,branch,four-door car,medsize
4,north west,9025,no,premium,bachelor,1/17/11,jan,medical leave,f,23675,...,33,31,0,7,personal auto,personal l2,offer1,branch,four-door car,medsize
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10684,central,15563,no,premium,bachelor,1/19/11,jan,unemployed,f,61541,...,12,40,0,7,personal auto,personal l1,offer3,web,luxury car,medsize
10685,north west,5259,no,basic,college,1/6/11,jan,employed,f,61146,...,7,68,0,6,personal auto,personal l3,offer2,branch,four-door car,medsize
10686,central,23893,no,extended,bachelor,2/6/11,feb,employed,f,39837,...,11,63,0,2,corporate auto,corporate l3,offer1,web,luxury suv,medsize
10687,west region,11971,no,premium,college,2/13/11,feb,employed,f,64195,...,0,27,4,6,personal auto,personal l1,offer1,branch,suv,medsize
10688,central,6857,no,basic,bachelor,1/8/11,jan,unemployed,m,68942,...,31,1,0,3,personal auto,personal l1,offer4,web,suv,medsize

In [22]:
feature_selection_pvalue(X,y)

ValueError: Pandas data cast to numpy dtype of object. Check input data with np.asarray(data). The types seen wereNone and const                            float64
region                            object
customer_lifetime_value            int64
response                          object
coverage                          object
education                         object
effective_to_date                 object
month                             object
employment_status                 object
gender                            object
income                             int64
location_code                     object
marital_status                    object
monthly_premium_auto               int64
months_since_last_claim            int64
months_since_policy_inception      int64
number_of_open_complaints          int64
number_of_policies                 int64
policy_type                       object
policy                            object
renew_offer_type                  object
sales_channel                     object
vehicle_class                     object
vehicle_size                      object
dtype: object. The data was
0         292
1         744
2         480
3         484
4         707
         ...
10684    1214
10685     273
10686     381
10687     618
10688    1021
Name: total_claim_amount, Length: 10689, dtype: int64
and
        const       region  customer_lifetime_value response  coverage  \
0        1.0      central                     4809       no     basic
1        1.0  west region                     2228       no     basic
2        1.0         east                    14947       no     basic
3        1.0   north west                    22332      yes  extended
4        1.0   north west                     9025       no   premium
...      ...          ...                      ...      ...       ...
10684    1.0      central                    15563       no   premium
10685    1.0   north west                     5259       no     basic
10686    1.0      central                    23893       no  extended
10687    1.0  west region                    11971       no   premium
10688    1.0      central                     6857       no     basic

      education effective_to_date month employment_status gender  ...  \
0       college           2/18/11   feb          employed      m  ...
1       college           1/18/11   jan        unemployed      f  ...
2      bachelor           2/10/11   feb          employed      m  ...
3       college           1/11/11   jan          employed      m  ...
4      bachelor           1/17/11   jan     medical leave      f  ...
...         ...               ...   ...               ...    ...  ...
10684  bachelor           1/19/11   jan        unemployed      f  ...
10685   college            1/6/11   jan          employed      f  ...
10686  bachelor            2/6/11   feb          employed      f  ...
10687   college           2/13/11   feb          employed      f  ...
10688  bachelor            1/8/11   jan        unemployed      m  ...

       months_since_last_claim months_since_policy_inception  \
0                            7                            52
1                            3                            26
2                           34                            31
3                           10                             3
4                           33                            31
...                        ...                           ...
10684                       12                            40
10685                        7                            68
10686                       11                            63
10687                        0                            27
10688                       31                             1

      number_of_open_complaints  number_of_policies     policy_type  \
0                             0                   9  corporate auto
1                             0                   1   personal auto
2                             0                   2   personal auto
3                             0                   2  corporate auto
4                             0                   7   personal auto
...                         ...                 ...             ...
10684                         0                   7   personal auto
10685                         0                   6   personal auto
10686                         0                   2  corporate auto
10687                         4                   6   personal auto
10688                         0                   3   personal auto

             policy  renew_offer_type  sales_channel  vehicle_class  \
0      corporate l3            offer3          agent  four-door car
1       personal l3            offer4    call center  four-door car
2       personal l3            offer3    call center            suv
3      corporate l3            offer2         branch  four-door car
4       personal l2            offer1         branch  four-door car
...             ...               ...            ...            ...
10684   personal l1            offer3            web     luxury car
10685   personal l3            offer2         branch  four-door car
10686  corporate l3            offer1            web     luxury suv
10687   personal l1            offer1         branch            suv
10688   personal l1            offer4            web            suv

      vehicle_size
0          medsize
1          medsize
2          medsize
3          medsize
4          medsize
...            ...
10684      medsize
10685      medsize
10686      medsize
10687      medsize
10688      medsize

[10689 rows x 24 columns]
before. After,
[ 292  744  480 ...  381  618 1021]
[[1.0 'central' 4809 ... 'agent' 'four-door car' 'medsize']
 [1.0 'west region' 2228 ... 'call center' 'four-door car' 'medsize']
 [1.0 'east' 14947 ... 'call center' 'suv' 'medsize']
 ...
 [1.0 'central' 23893 ... 'web' 'luxury suv' 'medsize']
 [1.0 'west region' 11971 ... 'branch' 'suv' 'medsize']
 [1.0 'central' 6857 ... 'web' 'suv' 'medsize']].

In [19]:
def train_and_evaluate(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    return mse